name: build AOSP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout Code
      uses: actions/checkout@v4

    - name: ⏰ Prepare timezone
      run: |
        sudo rm /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - name: 📦 Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y \
          bc bison build-essential cpio flex git wget curl lz4 \
          python-is-python3 libssl-dev libncurses5-dev libncursesw5-dev \
          zip unzip tar aria2 perl

    - name: 🔧 Clone Toolchains
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang
        git clone --depth=1 https://github.com/greenforce-project/gcc-arm64 -b master gcc64
        git clone --depth=1 https://github.com/greenforce-project/gcc-arm -b master gcc32

    - name: ⚙️ Setup Environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Jakarta date '+%d%m%Y-%H%M')" >> $GITHUB_ENV
        echo "CLANG_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV
        echo "GCC64_PATH=$GITHUB_WORKSPACE/gcc64" >> $GITHUB_ENV
        echo "GCC32_PATH=$GITHUB_WORKSPACE/gcc32" >> $GITHUB_ENV

    - name: 🔎 Debug Toolchains
      run: |
        echo "=== Clang Version ==="
        $CLANG_PATH/bin/clang --version
        echo "=== GCC64 Version ==="
        $GCC64_PATH/bin/aarch64-elf-gcc --version
        echo "=== GCC32 Version ==="
        $GCC32_PATH/bin/arm-eabi-gcc --version || true

    - name: 📥 Clone kernelSU-Next
      run: curl -LSs "https://raw.githubusercontent.com/Mr-Morat/KernelSU-Next/susfs/kernel/setup.sh" | bash -s susfs

    - name: 🔎 Debug Kernel Tree
      run: |
        echo "=== Kernel tree root ==="
        ls -lh
        echo "=== Check available defconfigs ==="
        ls arch/arm64/configs | grep sweet || true

    - name: 🛠️ Build Kernel
      run: |
        export ARCH=arm64
        export PATH="$CLANG_PATH/bin:$GCC64_PATH/bin:$GCC32_PATH/bin:$PATH"
        export KBUILD_BUILD_USER=nganu
        export KBUILD_BUILD_HOST=other_forger
        export KBUILD_COMPILER_STRING="$($CLANG_PATH/bin/clang --version | head -n 1)"

        make O=out sweet_defconfig || make O=out vendor/sweet_defconfig

        make -j$(nproc --all) O=out \
          ARCH=arm64 \
          LLVM=1 LLVM_IAS=1 CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-elf- \
          CROSS_COMPILE_ARM32=arm-eabi-

        mv out/.config out/sweet_defconfig.txt

    - name: 🔎 Debug Build Output
      run: |
        echo "=== Kernel build output ==="
        ls -lh out/arch/arm64/boot || true

    - name: 💾 Upload configs
      uses: actions/upload-artifact@v4
      with:
        name: configs-${{ env.BUILD_TIME }}
        path: out/sweet_defconfig.txt

    - name: 📂 Clone Anykernel3 & Package
      run: |
        git clone --depth=1 https://github.com/Mr-Morat/anykernel3 -b main AnyKernel3
        if [ -f "out/arch/arm64/boot/Image.gz-dtb" ]; then
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
        elif [ -f "out/arch/arm64/boot/Image.gz" ]; then
          cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
        elif [ -f "out/arch/arm64/boot/Image" ]; then
          cp out/arch/arm64/boot/Image AnyKernel3/Image
        else
          echo "❌ Tidak ada file kernel Image ditemukan!"
          exit 1
        fi
        [ -f "out/arch/arm64/boot/dtbo.img" ] && cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
        [ -f "out/arch/arm64/boot/dtb.img" ] && cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img
        cd AnyKernel3
        zip -r "../Blankont-AOSP-${{ env.BUILD_TIME }}.zip" *

    - name: 📤 Upload Flashable zip
      uses: actions/upload-artifact@v4
      with:
        name: Blankont-AOSP-${{ env.BUILD_TIME }}
        path: Blankont-AOSP-${{ env.BUILD_TIME }}.zip
